name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch (e.g., 'vite')
  push:
    branches: ["vite"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Setup Node.js (installing dependencies, build tools, etc.)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'  # Choose the appropriate version for your Vite project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Vite project (generates static files in 'dist/')
      - name: Build the project
        run: npm run build

      # Step 5: Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 6: Upload the build folder (usually 'dist/') as an artifact for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'  # Upload the 'dist' folder that contains the static content

      # Step 7: Deploy the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
